### PR TITLE
Refactored authentication and user routes: Moved validatePassword and…

### PR DESCRIPTION
**Pull request by vsrodriguez3**
… resetPassword to authRoutes; created userRoutes and userController.

## **Description**

1) **What does this PR do?**  
   This PR organizes routing of user and authentication endpoints. It ensures better file structure.

2) **List of changes:**  
   - Moved `validatePassword` and `resetPassword` routes to `authRoutes.js` and their logic to `authController.js`.  
   - Created a new route to fetch all users in `userRoutes.js` and its logic in `userController.js`.  
   - Removed user-related routes from `testRoutes.js` 
   - Updated the `app.js` file to reflect these changes by including the new `userRoutes`  

---

## **Type of Changes**

- Feature update  
- Code refactoring  

---

## **Acceptance Criteria**

- User-related functionality is properly refactored into `userRoutes.js` and `userController.js`.  
- Authentication routes (`validatePassword` and `resetPassword`) are moved to `authRoutes.js` and `authController.js`.  
- All routes are functional.  

---

### **Before**
- User and auth logic were all over `testRoutes.js`.
- No clear separation of concerns between authentication and user-related logic.

### **After**
- User-related routes in `userRoutes.js`:
  - `GET /api/v1/users`
  - `PUT /api/v1/users/:id`
  - `DELETE /api/v1/users/:id`
- Authentication-related routes in `authRoutes.js`:
  - `POST /api/v1/auth/validate-password`
  - `POST /api/v1/auth/reset-password`

---

## **Testing Instructions**

1. **Start the Server**
   - Run `npm run dev` in the terminal.

2. **Test User Routes**
   - Use Postman:
     - **Create a New User**:  
       - **URL**: `POST http://localhost:8000/api/v1/users`  
       - **Body (JSON)**:
         ```json
         {
           "name": "John Doe",
           "email": "john.doe@example.com",
           "password": "SecurePassword123",
           "role": "admin",
           "store": "Main Clinic"
         }
         ```
       - **Expected Response**:
         ```json
         {
           "success": true,
           "message": "User created successfully",
           "data": {
             "name": "John Doe",
             "email": "john.doe@example.com",
             "role": "admin",
             "store": "Main Clinic",
             "_id": "64f1d3e292ebf8a2cd456abc",
             "createdAt": "2024-11-24T12:00:00.000Z",
             "updatedAt": "2024-11-24T12:00:00.000Z"
           }
         }
         ```
     - **Get All Users**:  
       - `GET http://localhost:8000/api/v1/users`  
       - No body required.  
     - **Update User**:  
       - `PUT http://localhost:8000/api/v1/users/:id`  
       - Body example:
         ```json
         {
           "role": "inventoryManager"
         }
         ```
     - **Delete User**:  
       - `DELETE http://localhost:8000/api/v1/users/:id`

3. **Test Auth Routes**
   - Use Postman:
     - **Validate Password**:  
       - `POST http://localhost:8000/api/v1/auth/validate-password`  
       - Body example:
         ```json
         {
           "email": "jane.doe@example.com",
           "password": "SecurePassword123"
         }
         ```
     - **Reset Password**:  
       - `POST http://localhost:8000/api/v1/auth/reset-password`  
       - Body example:
         ```json
         {
           "email": "jane.doe@example.com",
           "currentPassword": "SecurePassword123",
           "newPassword": "NewSecurePassword456"
         }
         ```

4. **Verify**
   - Ensure all responses return the expected results.

---

## **Learnings (Optional)**

- Keeping routes and controllers organized improves code readability and maintainability.

### CODE REVIEW

**Review by up2code3 — APPROVED** [review]
Everything worked for the usual CRUD stuff, Do we want find a single user? and then for the password validate and reset , I could only get it to work on users I created, BUT... I think that was only because I created the users with the seed-database branch, then I fetched and ran the server on the Refactor Branch , So I think it was confused about that, I almost 99% sure, that once both branches are as one it will not be a problem. for example I bet it works on your machine because you have all the files, when I use the refactor branch, I know longer have the Seed-database.js code. I think maybe the hashing is getting confused. 

does that make sense @GinaCastromonte am I even close to being on the right track?

**Review by GinaCastromonte — APPROVED** [review]
Great job on this PR, Vanessa! You and Tristan  @up2code3 have done an excellent job structuring the backend. I have a couple of suggestions to make it even more secure:

Consider adding middleware to handle user access control. This could include determining whether only admins have access or if both admins and users (updating their own information) can access specific routes. This would enhance the clarity and security of your API's permissions.

Incorporating bcrypt for password hashing during signup and for password verification when logging in would significantly improve the security of user credentials.

**Comment by up2code3** [comment]
> Great job on this PR, Vanessa! You and Tristan @up2code3 have done an excellent job structuring the backend. I have a couple of suggestions to make it even more secure:
> 
> Consider adding middleware to handle user access control. This could include determining whether only admins have access or if both admins and users (updating their own information) can access specific routes. This would enhance the clarity and security of your API's permissions.
> 
> Incorporating bcrypt for password hashing during signup and for password verification when logging in would significantly improve the security of user credentials.

for the BCrypt on login and sign up , is that not applied from the pre/save thing  in the user model with the salt and the hash? or does it need to be called other places too... ?

**Comment by up2code3** [comment]
@GinaCastromonte , for the access control middleware, is that something we could add to roleMiddleware,js? or does roleMiddleware cover that?

**Comment by GinaCastromonte** [comment]
@up2code3   sorry I didn't see you implemented bcrypt for password hashing in the userModel. 

For better access control, you would update the userRoutes.js file to include the authenticate and roleMiddleware. 
 Ex.  Create a new user (Admin only)
 `router.post("/", authenticate, roleMiddleware(["admin"]), createUser);
`.

**Comment by up2code3** [comment]
@vsrodriguez3 
@GinaCastromonte 
Would that be something like this?

router.post("/", authenticate, roleMiddleware(["admin"]), createUser); <-- so only admins can create 
router.get("/", authenticate, roleMiddleware(["admin"],["clerk"],["inventory-manager"), getAllUser); <-- everybody can see the list
router.delete("/", authenticate, roleMiddleware,["inventory-manager"), getAllUser); <-- only manager can delete,

and so on, and so on, for all the Crud Operations for users, So each Crud operation will be listed and then what users can do each. and then do the same for inventory too?

btw, Would we define what users can create/delete medications in the userRoutes or in the medicationRoutes?

**Comment by up2code3** [comment]
I was having trouble logging in, So I did these 2 things, and it worked. It shouldn't effect any other functionality. 
Screenshot 2024-11-29 125348
#1 Made up a JWT Secret on line 3 of my .env file. and then,
Screenshot 2024-11-29 125323
in server.js I added line 3. And it seem to do the trick , I got a  "Login Successful on Postman", After that I did a add, commit, push , on the refactor-routes-and-controllers branch

**Comment by up2code3** [comment]
I just did a commit for better access control, I tested by logging in with JJ@mail.com (password is Secure22 and admin role), and did get all users , worked great, then I logged in with DD@mail.com (password also Secure22 and clerk role) , this time for get all users, I got access denied. When I switch from DD to JJ I also changed the bearer token for that user.  I do see some conflicts, I am going to resolve those now.

**Comment by up2code3** [comment]
And nice, I think we are all good now.

**Comment by up2code3** [comment]
oh yea, I set all of the CRUD routes to admin, But the next time we talk we can decide who should have access to what. I just thought this would be uniform and most straight forward to understand , by having them all set to admin at the moment.

**Comment by GinaCastromonte** [comment]
User routes take care of all the important tasks related to users, like creating, updating, and removing user accounts, along with managing the unique permissions for each user. Medication routes focus on the essential CRUD operations for medications, which include adding, updating, deleting, or simply viewing the medications that are available.  I tested it and it's all working as it should! Great job

**Comment by up2code3** [comment]
Nice!!! @vsrodriguez3 Do You want the Honors of pressing the Merge Pull Request Button?!

**Pull request merged**
